package by.student.trainDesign.domain;

public enum Station {
    BREST_CENTRAL, BREST_EAST, BREST_POLESSKY, GRODNO, GOMEL,
    GOMEL_NORTH, MOGILEV_1, MOGILEV_2, MOGILEV_3, MOGILEV_PODOLSKY,
    VITEBSK, MINSK_PASSENGER, MINSK_NORTH, MINSK_SOUTH;
}
